### ISSUE TITLE
Code for real-world implementation

### ISSUE THREAD

**Issue by yijionglin** [hyperplane-lab/RLAfford#10]
Hi there,

Thanks for sharing such a well-developed project!

Just wondering if you have any plans to open-source the code for real-world implementation.

All the best,

**Comment by GengYiran** [comment]
you can find the code for the real-world experiments training code in experiments.md->real world

**Comment by GengYiran** [comment]
the env of real world is here： https://github.com/hyperplane-lab/RLAfford/blob/main/MARL_Module/envs/tasks/franka_cabinet_real_world.py
