### ISSUE TITLE
Physical experiments

### ISSUE THREAD

**Issue by duidui6666** [hyperplane-lab/RLAfford#12]
I would like to ask if the eyes are outside the hands in the real experiments? Another question is the A Digital Twin System used in the physical experiment, which I am a little curious about, and the last question, which is mentioned in the article, is there a movable base on the arm, but it seems that I did not see it in the actual experiment.

**Comment by GengYiran** [comment]
good question！we use eyes on base in real world system, we also train a policy for the real world experiment that the arm cannot move on the base, you can find the related code in the experiment.txt->real world.

**Comment by GengYiran** [comment]
the env of real world is here： https://github.com/hyperplane-lab/RLAfford/blob/main/MARL_Module/envs/tasks/franka_cabinet_real_world.py

**Comment by duidui6666** [comment]
Thank you very much, I was just looking for it for a while.
