### ISSUE TITLE
about model weights

### ISSUE THREAD

**Issue by SshiJwu** [hyperplane-lab/RLAfford#13]
Hi,can you release your model weights?

**Comment by GengYiran** [comment]
ok, we will collect some models

**Comment by boshi-an** [comment]
We uploaded some but not all trained model weights for our task Open Door and Open Drawer, with our method "RL + Collision Predictor". You can find the saved checkpoints in [sample_checkpoints.zip](https://github.com/hyperplane-lab/RLAfford/blob/main/example_check_points.zip).
