### ISSUE TITLE
why there is AssertionError happened in MARL_MOUDLE/envs/tasks  when i run this project?

### ISSUE THREAD

**Issue by Psycho-9** [hyperplane-lab/RLAfford#3]

**Comment by GengYiran** [comment]
Can you provide a screenshot of the error report, or provide the specific content of the error report?

**Comment by Psycho-9** [comment]
the error when i run the ## Close Door  ### State experiment is as follows
Simulator: number of environments 352
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    train()
  File "train.py", line 48, in train
    task, env = parse_task(args, cfg, cfg_train, sim_params, agent_index, logdir)
  File "/home/pyf/RLAfford-main/MARL_Module/envs/utils/parse_task.py", line 80, in parse_task
    task = eval(args.task)(
  File "/home/pyf/RLAfford-main/MARL_Module/envs/tasks/franka_cabinet.py", line 57, in __init__
    assert(self.env_num_train % self.cabinet_num_train == 0)
AssertionError
Printing Profile:
End of Profile

**Comment by boshi-an** [comment]
For simplicity for implement, every object should be replicated for the same number. Which means # of different objects (cabinet_num_train) should be a factor of # of total environments. You can assign proper numbers in the command line when running the code using --num_xxx=xxx.

**Comment by Psycho-9** [comment]
how can i know the proper number of each experiments?

**Comment by GengYiran** [comment]
First, you can modify the number of objects or object types through the parameters in the python command or the config of the task, just make sure that the number of objects is a multiple of the object types (e.g., 4 objects of 2 types). Second, our experiments generally use the most objects to train, you can refer to the number of objects listed in the config is the upper limit of object types (of course, you can also add your own object dataset).

**Comment by GengYiran** [comment]
![image](https://user-images.githubusercontent.com/75480302/224517124-4b4ff4ae-bf15-4431-896e-bdb675ffc982.png)
![image](https://user-images.githubusercontent.com/75480302/224517139-3ad14380-9457-4048-a27a-8c80deac838b.png)
