### ISSUE TITLE
pc RL env franka actor create problem: "free(): invalid pointer"

### ISSUE THREAD

**Issue by ChengYaofeng** [hyperplane-lab/RLAfford#7]
when I run all the pc RL env tasks like franka_cabinet_PC_partial, I meet error ---- free(): invalid pointer. And I checked the error location, it occurred on line `franka_actor = self.gym.create_actor(env_ptr, self.franka_asset, initial_franka_pose, "franka", env_id, 2, 0)` of `franka_cabinet.py`. It happens in all the pc tasks, and in the `_place_agents` function's `for env_id in range(env_num):` iteration.  I can create the franka_actor 79 times and then the error occurs. Do you have any idea of this issue?

**Comment by ChengYaofeng** [comment]
OK, I found the answer. It is because the default env_num is too much for my GPU RAM(NV 3060 12G), I reduced the number of env to 40 and it can run well, which took about 8G GPU RAM.

**Comment by GengYiran** [comment]
Yes. This is a common problem that can usually be solved by changing the number of environments
